#!/usr/bin/env python3

import os 
import sys
import nltk
import helpers

from termcolor import colored
from analyzer import Analyzer

# TODO
def main():
    
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Error, usage: ./tweets @user")
    user = sys.argv[1].lstrip("@")    
    
    
    #get Tweets
    user_tweets = helpers.get_user_timeline(user, 50)
    if user_tweets == None :
        sys.exit("Error: problem getting tweets")
        
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    #analayze tweets
    for tweet in user_tweets:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{}{}".format(score,tweet,),"green"))
        elif score < 0.0:
            print(colored("{}{}".format(score,tweet,),"red"))
        else:
            print(colored("{}{}".format(score,tweet,),"yellow"))

if __name__ == "__main__":
    main()

    
